[project]
name = "pi-camera-stream-flask"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "opencv-contrib-python>=4.11.0.86 ; sys_platform == 'linux'",
    "picamera2 ; sys_platform == 'linux'",
]
